export const colors: { [key: string]: string } = {
  data_table_wrapper: '#364EA2',
  data_table_header: '#DDE1EF',
  success_status_outline: '#0E9C6C',
  success_status_bg: '#EBFEF8',
  reject_status_outline: '#E62112',
  reject_status_bg: '#FFF2F0',
  pending_status_outline: '#FFB727',
  pending_status_bg: '#FFFCF6',
  required_status_outline: '#8E8E8E',
  required_status_bg: '#F8F8F8',
  Food: '#E7ECFC',
  Nature: '#E3EFF8',
  Travel: '#E3F7F8',
  Jungle: '#E7ECFC',
  Trekking: '#E3EFF8',
  Wildlife: '#E3F7F8',
};
