// app/layout.tsx or wherever your RootLayout is defined

import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import './globals.css';
import SessionProviderWrapper from './providers/SessionProviderWrapper';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} font-markForMC`}>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
