import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import './globals.css';
import SessionProviderWrapper from '@/providers/SessionProviderWrapper';
import { TeamMemberProvider } from '@/store/TeamMemberContext';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} font-markForMC`}>
        <SessionProviderWrapper>
          <TeamMemberProvider>{children}</TeamMemberProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
